---
name: docker-build

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      namespace:
        required: false
        type: string
        default: ${{ github.repository }}
      tag:
        required: false
        type: string
        default: "${{ github.sha }}"
      registry:
        required: false
        type: string
        default: ghcr.io
      push:
        required: false
        type: boolean
        default: true
      cache:
        required: false
        type: boolean
        default: true
      context:
        required: false
        type: string
        default: .
      file:
        required: false
        type: string
        default: Dockerfile
      build-args:
        required: false
        type: string
    secrets:
      REGISTRY_LOGIN:
        required: false
      REGISTRY_PASSWORD:
        required: false

jobs:
  build:
    env:
      REGISTRY_LOGIN: "${{ secrets.REGISTRY_LOGIN || github.repository_owner }}"
      REGISTRY_PASSWORD: "${{ secrets.REGISTRY_PASSWORD || secrets.GITHUB_TOKEN }}"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildk
      uses: docker/setup-buildx-action@v1

    - name: Login to ${{ inputs.registry }}
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.registry }}
        username: ${{ env.REGISTRY_LOGIN }}
        password: ${{ env.REGISTRY_PASSWORD }}

    - name: Build and push ${{ inputs.name }} image
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.context }}
        push: ${{ inputs.push }}
        tags: ${{ inputs.registry }}/${{ inputs.namespace }}/${{ inputs.name }}:${{ inputs.tag }}
        cache-from: type=gha,scope=${{ inputs.name }}
        cache-to: type=gha,mode=max,scope=${{ inputs.name }}
        build-args: ${{ inputs.build-args }}
        file: ${{ inputs.file }}
