---
name: docker-build

on:
  workflow_call:
    inputs:
      namespace:
        required: false
        type: string
        default: ${{ github.repository }}
      tag:
        required: false
        type: string
        default: "${{ github.sha }}"
      registry:
        required: false
        type: string
        default: ghcr.io
      push:
        required: false
        type: boolean
        default: true
      cache:
        required: false
        type: boolean
        default: true
      context:
        required: false
        type: string
        default: .
      file:
        required: false
        type: string
        default: Dockerfile
      build-args:
        required: false
        type: string
    secrets:
      REGISTRY_LOGIN:
        required: false
      REGISTRY_PASSWORD:
        required: false

jobs:
  build:
    env:
      REGISTRY_LOGIN: "${{ secrets.REGISTRY_LOGIN }}"
      REGISTRY_PASSWORD: "${{ secrets.REGISTRY_PASSWORD }}"
      CACHE_KEY: "${{ format('{0}-{1}', inputs.context, inputs.file) }}"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildk
      uses: docker/setup-buildx-action@v1

    - name: Login to Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.registry }}
        username: ${{ secrets.REGISTRY_LOGIN }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
      if: ${{ env.REGISTRY_LOGIN != '' && env.REGISTRY_PASSWORD != '' }}

    - name: Build and push vault image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ matrix.build.name }}:${{ env.TAG }}
        cache-from: type=gha,scope=${{ env.CACHE_KEY }}
        cache-to: type=gha,mode=max,scope=${{ env.CACHE_KEY }}
        build-args: ${{ inputs.build-args }}
