on: push

jobs:
  docker-build:
    uses: ./.github/workflows/docker-build.yaml
    with:
      context: tests/docker
      name: test

  trivy:
    needs: docker-build
    uses: scality/workflows/.github/workflows/trivy.yaml@main
    with:
      image-ref: 'ghcr.io/${{ github.repository }}/test:${{ github.sha }}'
