on: push

jobs:
  docker-build:
    uses: ./.github/workflows/docker-build.yaml
    with:
      context: tests/docker
      name: test

  trivy:
    needs: docker-build
    uses: ./.github/workflows/trivy.yaml
    with:
      name: trivy_test
