on: pull_request

permissions:
  packages: write
  contents: read
  security-events: write
  pull-requests: write

jobs:
  docker-build:
    uses: ./.github/workflows/docker-build.yaml
    with:
      context: tests/docker
      name: test
  docker-build-with-secrets:
    uses: ./.github/workflows/docker-build.yaml
    with:
      context: tests/docker-secrets
      name: test-secrets
      secrets: |
        my_secret=toto
        my_other_secret=tata

  trivy:
    needs: docker-build
    uses: ./.github/workflows/trivy.yaml
    with:
      name: '/test'

  lfs-warning:
    uses: ./.github/workflows/lfs-warning.yaml
