on: push

jobs:
  docker-build:
    uses: ./.github/workflows/docker-build.yaml
    with:
      context: tests/docker
      name: test

  trivy:
    needs: docker-build
    name: Trivy Vulnerability Scan for Docker images
    uses: scality/workflows/.github/workflows/trivy.yaml@main
    with:
      image-ref: '${{ inputs.registry }}/${{ inputs.namespace }}/${{ inputs.name }}:${{ inputs.tag }}'
