on: pull_request

permissions:
  packages: write
  contents: read
  security-events: write

jobs:
  docker-build:
    uses: ./.github/workflows/docker-build.yaml
    with:
      context: tests/docker
      name: test

  trivy:
    needs: docker-build
    uses: ./.github/workflows/trivy.yaml
    with:
      name: '/test'

  file-check:
    uses: ./.github/workflows/file-check.yaml