---
name: trivy

on:
  workflow_call:
    inputs:
      image-ref:
        default: "ghcr.io/${{ github.repository }}:${{ github.sha }}"
        required: false
        type: string

jobs:
  trivy:
    env:
      REGISTRY_LOGIN: "${{ secrets.REGISTRY_LOGIN || github.repository_owner }}"
      REGISTRY_PASSWORD: "${{ secrets.REGISTRY_PASSWORD || secrets.GITHUB_TOKEN }}"
      FILE: ${{ inputs.file || format('{0}/Dockerfile', inputs.context) }}
    name: Trivy Vulnerability Scan for images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ inputs.image-ref }}
          format: 'sarif'
          output: 'trivy-image-results.sarif'
          ignore-unfixed: true
          vuln-type: 'os,library'

      - name: Upload Trivy Image scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-image-results.sarif'
          category: 'image'
