---
name: trivy
on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      namespace:
        required: false
        type: string
        default: "${{ github.repository }}"
      tag:
        required: false
        type: string
        default: "${{ github.sha }}"
      registry:
        required: false
        type: string
        default: "ghcr.io"
    secrets:
      REGISTRY_LOGIN:
        required: false
      REGISTRY_PASSWORD:
        required: false

jobs:
  trivy:
    env:
      TRIVY_USERNAME: "${{ secrets.REGISTRY_LOGIN || github.repository_owner }}"
      TRIVY_PASSWORD: "${{ secrets.REGISTRY_PASSWORD || secrets.GITHUB_TOKEN }}"
    name: Trivy Vulnerability Scan for images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Image Scan
        uses: aquasecurity/trivy-action@0.28.0
        # Due to rate limiting faced by aquasecurity/trivy-action#389 we download the DBs
        # from the public ECR repository
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db
          TRIVY_JAVA_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-java-db
        with:
          image-ref: "${{ inputs.registry }}/${{ inputs.namespace }}/${{ inputs.name }}:${{ inputs.tag }}"
          format: 'sarif'
          output: 'trivy-image-results.sarif'
          ignore-unfixed: true
          vuln-type: 'os,library'

      - name: Upload Trivy Image scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-image-results.sarif'
          category: 'image'
